Workaround invalid songs
mopidy/mopidy-gmusic pull request #159
Opened 2016-11-30 03:13 UTC by jbtheou

A song can be corrupted. By catching KeyError, we avoid the
thread to crash.

This allow for example to complete properly a refresh of the
songs list.

2016-11-30 07:02 UTC, belak commented
Do you have any examples of songs where this pops up? I haven't see this before.

2016-11-30 10:03 UTC, belak requested changes
Thanks for your contribution!

Overall, I'd be interested in seeing what's actually causing this... since I haven't run across any problems like this before and I'd like to avoid them in the future.

If this does need a fix, I'd rather avoid the KeyError entirely and just have fallbacks for the title and any other field accessed directly, so we don't have to copy the whole Track creation.

2016-11-30 10:03 UTC, belak commented on mopidy_gmusic/library.py
> +               name=song['title'],
This could be removed from the try-catch and replaced with song.get('title', 'Unknown')

2016-11-30 10:03 UTC, belak commented on mopidy_gmusic/library.py
> +               length=int(song['durationMillis']),
This could be simplified similarly to the above change.

2016-11-30 14:53 UTC, jbtheou commented
I dumped the traces for my songs, and it looks like that:

 {u'kind': u'sj#track', u'deleted': False, u'trackType': u'8', u'lastModifiedTimestamp': u'1448049984522600', u'storeId': u'REMOVED BY ME', u'recentTimestamp': u'1422557902656000', u'clientId': u'REMOVED BY ME', u'albumId': u'B2dikhav7ozv7rk2r6kaj6nc6jy', u'artistId': [u'A24gk2572zt4vmycn6y2z6xjs3y'], u'nid': u'T3ghs7y6mj57jzwitohqoj4gbnq', u'playCount': 4, u'artistArtRef': [{u'url': u'http://lh3.googleusercontent.com/7df5wOlQT4y-sG4HSwYgglaYUTmYZcc2lTkCzk6eugRsvhoj-q65R3odb7BB01YR7ZjRI_NoRQ', u'kind': u'sj#imageRef', u'aspectRatio': u'2', u'autogen': True}], u'creationTimestamp': u'1422556716244071', u'id': u'4f606d6f-c1a2-3e62-bfba-964673464951'}

Which seems to be an invalid song. Maybe just discard those songs would be better? 
Let me know your thoughts here. Otherwise the changes you propose are indeed needed.

2016-11-30 19:01 UTC, belak commented
That track shows up for me with a title:

```
{u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/lOq-Duf9ONXy61RrpoVqPqUSRSktmUywp4IchrQF9ouGVsoPXqtiRIirC0TU8iZPq6SZw7dM', u'kind': u'sj#imageRef', u'aspectRatio': u'1', u'autogen': False}], u'artistId': [u'A24gk2572zt4vmycn6y2z6xjs3y'], u'composer': u'', u'year': 2003, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'H\xe9ritage', u'title': u'Vie Meilleure', u'albumArtist': u"Neg'Marrons", u'trackNumber': 6, u'discNumber': 1, u'albumAvailableForPurchase': False, u'explicitType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'T3ghs7y6mj57jzwitohqoj4gbnq', u'nid': u'T3ghs7y6mj57jzwitohqoj4gbnq', u'estimatedSize': u'11481365', u'albumId': u'B2dikhav7ozv7rk2r6kaj6nc6jy', u'genre': u'International Hip-Hop', u'kind': u'sj#track', u'artist': u"Neg'Marrons", u'durationMillis': u'286000'}
```

Google's APIs are pretty inconsistent at times, so sometimes these problems fix themselves. I still think your fix would be worthwhile though, that way we at least show something for them.

Are you subscribed to All-Access, or is this an uploaded/purchased track? There was a bug relating to this I never quite managed to track down.

2016-11-30 19:06 UTC, jbtheou commented
I am All-Access. 
The main issue is that without this fix, on my side, the refresh of my library crashed on the middle, and I ends up with just a part of my library. Removing faulty songs is not a big deal for me, while not having most of my library because of a crash is. 

Can you modify the code on your side? Or do you prefer if I push a new pull request?

2016-11-30 19:17 UTC, belak commented
You should just be able to push a new commit to your branch (or rewrite the existing one) and it will show up in this PR.

I guess I'd prefer to drop missing songs and log them.

2016-11-30 19:19 UTC, jbtheou commented
Sounds good to me to actually drop the song with a warning on the logs. I guess this cannot be done inside this function. I will look around to code, but if you have a pretty good idea how to implement it and you have a bit of time, don't hesitate ;-)

2016-11-30 19:21 UTC, belak commented
I'm curious - do you get the full track if you add print(self.session.api.get_track_info('T3ghs7y6mj57jzwitohqoj4gbnq')) somewhere in backend.py after the login?

2016-11-30 19:25 UTC, jbtheou commented
I will try this later today (I don't have access to my setup now). On the meantime, I changed the patch in case we want keep the idea.

2016-12-02 02:57 UTC, jbtheou commented
Sorry for the delay.
I do get the proper answer:

 {u'albumArtRef': [{u'url': u'http://lh6.ggpht.com/lOq-Duf9ONXy61RrpoVqPqUSRSktmUywp4IchrQF9ouGVsoPXqtiRIirC0TU8iZPq6SZw7dM', u'kind': u'sj#imageRef', u'aspectRatio': u'1', u'autogen': False}], u'artistId': [u'A24gk2572zt4vmycn6y2z6xjs3y'], u'composer': u'', u'year': 2003, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'H\xe9ritage', u'title': u'Vie Meilleure', u'albumArtist': u"Neg'Marrons", u'trackNumber': 6, u'discNumber': 1, u'albumAvailableForPurchase': False, u'explicitType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'T3ghs7y6mj57jzwitohqoj4gbnq', u'nid': u'T3ghs7y6mj57jzwitohqoj4gbnq', u'estimatedSize': u'11481365', u'albumId': u'B2dikhav7ozv7rk2r6kaj6nc6jy', u'genre': u'International Hip-Hop', u'kind': u'sj#track', u'artist': u"Neg'Marrons", u'durationMillis': u'286000'}

But during the refresh, I still get the same error as before. So there is something different between the two ways of accessing the song

2016-12-18 03:18 UTC, belak commented
So, this may be an odd question, but if you remove the track from your library and re-add it, does this still happen?

2020-12-06 23:32 UTC, jodal commented
Closing because Google Play Music has been shut down, and this project is being discontinued.

2020-12-06 23:32 UTC, closed without merging